# Generated by Django 5.2.5 on 2025-08-29 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arbitro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=120)),
                ('nombre', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('horario', models.TimeField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('suma_puntos_general', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['torneo__liga__temporada', 'torneo__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('escudo_url', models.URLField(blank=True)),
                ('direccion', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Fecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('fecha', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ronda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Fase Única', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(blank=True, max_length=120)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipos', to='ligas.categoria')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='ligas.club')),
            ],
            options={
                'unique_together': {('club', 'categoria')},
            },
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=120)),
                ('nombre', models.CharField(max_length=120)),
                ('dni', models.CharField(blank=True, max_length=20)),
                ('fecha_nac', models.DateField(blank=True, null=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='ligas.equipo')),
            ],
            options={
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('temporada', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['-temporada', 'nombre'],
                'unique_together': {('nombre', 'temporada')},
            },
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_hora', models.DateTimeField(blank=True, null=True)),
                ('goles_local', models.PositiveIntegerField(default=0)),
                ('goles_visitante', models.PositiveIntegerField(default=0)),
                ('jugado', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('arbitro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ligas.arbitro')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidos', to='ligas.categoria')),
                ('fecha_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='ligas.fecha')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidos_local', to='ligas.equipo')),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidos_visitante', to='ligas.equipo')),
            ],
            options={
                'unique_together': {('fecha_ref', 'categoria', 'local', 'visitante')},
            },
        ),
        migrations.CreateModel(
            name='EventoPartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minuto', models.PositiveIntegerField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('GOL', 'Gol'), ('TA', 'Tarjeta Amarilla'), ('TR', 'Tarjeta Roja'), ('WO', 'Walkover')], max_length=3)),
                ('detalle', models.CharField(blank=True, max_length=200)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='ligas.equipo')),
                ('jugador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ligas.jugador')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='ligas.partido')),
            ],
        ),
        migrations.CreateModel(
            name='ReglaPuntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_victoria', models.IntegerField(default=3)),
                ('puntos_empate', models.IntegerField(default=1)),
                ('puntos_derrota', models.IntegerField(default=0)),
                ('puntos_walkover_ganador', models.IntegerField(default=3)),
                ('puntos_walkover_perdedor', models.IntegerField(default=0)),
                ('diferencia_maxima_goles', models.PositiveIntegerField(default=0)),
                ('categoria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='regla_puntos', to='ligas.categoria')),
            ],
        ),
        migrations.AddField(
            model_name='fecha',
            name='ronda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fechas', to='ligas.ronda'),
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='torneos', to='ligas.liga')),
            ],
            options={
                'ordering': ['liga__temporada', 'nombre'],
                'unique_together': {('liga', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='ronda',
            name='torneo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rondas', to='ligas.torneo'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='torneo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='ligas.torneo'),
        ),
        migrations.AlterUniqueTogether(
            name='fecha',
            unique_together={('ronda', 'numero')},
        ),
        migrations.CreateModel(
            name='TablaPosicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField(default=0)),
                ('pj', models.PositiveIntegerField(default=0)),
                ('pg', models.PositiveIntegerField(default=0)),
                ('pe', models.PositiveIntegerField(default=0)),
                ('pp', models.PositiveIntegerField(default=0)),
                ('gf', models.PositiveIntegerField(default=0)),
                ('gc', models.PositiveIntegerField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabla', to='ligas.categoria')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabla', to='ligas.equipo')),
            ],
            options={
                'ordering': ['-puntos', '-pg', 'gc'],
                'unique_together': {('categoria', 'equipo')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='ronda',
            unique_together={('torneo', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together={('torneo', 'nombre')},
        ),
    ]
