# Generated by Django 5.2.5 on 2025-08-29 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ligas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arbitro',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Árbitro', 'verbose_name_plural': 'Árbitros'},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['torneo__liga__temporada', 'torneo__nombre', 'nombre'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='club',
            options={'ordering': ['nombre'], 'verbose_name': 'Club', 'verbose_name_plural': 'Clubes'},
        ),
        migrations.AlterModelOptions(
            name='equipo',
            options={'ordering': ['categoria__torneo__liga__temporada', 'categoria__nombre', 'club__nombre'], 'verbose_name': 'Equipo', 'verbose_name_plural': 'Equipos'},
        ),
        migrations.AlterModelOptions(
            name='eventopartido',
            options={'ordering': ['partido_id', 'minuto', 'id'], 'verbose_name': 'Evento de partido', 'verbose_name_plural': 'Eventos de partido'},
        ),
        migrations.AlterModelOptions(
            name='fecha',
            options={'ordering': ['ronda__torneo__liga__temporada', 'ronda__torneo__nombre', 'numero'], 'verbose_name': 'Fecha', 'verbose_name_plural': 'Fechas'},
        ),
        migrations.AlterModelOptions(
            name='jugador',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Jugador', 'verbose_name_plural': 'Jugadores'},
        ),
        migrations.AlterModelOptions(
            name='liga',
            options={'ordering': ['-temporada', 'nombre'], 'verbose_name': 'Liga', 'verbose_name_plural': 'Ligas'},
        ),
        migrations.AlterModelOptions(
            name='partido',
            options={'ordering': ['fecha_ref__ronda__torneo__liga__temporada', 'fecha_ref__ronda__torneo__nombre', 'fecha_ref__numero'], 'verbose_name': 'Partido', 'verbose_name_plural': 'Partidos'},
        ),
        migrations.AlterModelOptions(
            name='reglapuntos',
            options={'verbose_name': 'Regla de puntos', 'verbose_name_plural': 'Reglas de puntos'},
        ),
        migrations.AlterModelOptions(
            name='ronda',
            options={'ordering': ['torneo__liga__temporada', 'torneo__nombre', 'nombre'], 'verbose_name': 'Ronda', 'verbose_name_plural': 'Rondas'},
        ),
        migrations.AlterModelOptions(
            name='tablaposicion',
            options={'ordering': ['-puntos', '-pg', 'gc', '-gf'], 'verbose_name': 'Tabla de posiciones', 'verbose_name_plural': 'Tablas de posiciones'},
        ),
        migrations.AlterModelOptions(
            name='torneo',
            options={'ordering': ['liga__temporada', 'nombre'], 'verbose_name': 'Torneo', 'verbose_name_plural': 'Torneos'},
        ),
    ]
