# Generated by Django 5.2.6 on 2025-09-24 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ligas", "0005_categoria_liga"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categoria",
            options={
                "ordering": ["liga__temporada", "liga__nombre", "nombre"],
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
            },
        ),
        migrations.AlterModelOptions(
            name="equipo",
            options={
                "ordering": [
                    "categoria__liga__temporada",
                    "categoria__nombre",
                    "club__nombre",
                ],
                "verbose_name": "Equipo",
                "verbose_name_plural": "Equipos",
            },
        ),
        migrations.CreateModel(
            name="PartidoFixture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ronda",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Ronda 1 (Ida)"), (2, "Ronda 2 (Vuelta)")]
                    ),
                ),
                ("fecha_nro", models.PositiveIntegerField()),
                ("jugado", models.BooleanField(default=False)),
                ("goles_local", models.IntegerField(default=0)),
                ("goles_visitante", models.IntegerField(default=0)),
                ("fecha_programada", models.DateTimeField(blank=True, null=True)),
                (
                    "club_local",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="partidos_fixture_local",
                        to="ligas.club",
                    ),
                ),
                (
                    "club_visitante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="partidos_fixture_visitante",
                        to="ligas.club",
                    ),
                ),
                (
                    "torneo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partidos_fixture",
                        to="ligas.torneo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partido de fixture",
                "verbose_name_plural": "Partidos de fixture",
                "ordering": [
                    "torneo__liga__temporada",
                    "torneo__nombre",
                    "ronda",
                    "fecha_nro",
                    "club_local__nombre",
                ],
                "unique_together": {
                    ("torneo", "ronda", "fecha_nro", "club_local", "club_visitante")
                },
            },
        ),
    ]
