# Generated by Django 5.2.6 on 2025-09-24 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ligas", "0005_categoria_liga"),
    ]

    operations = [
        migrations.CreateModel(
            name="FixturePartido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ronda",
                    models.SmallIntegerField(
                        choices=[(1, "Ronda 1 (Ida)"), (2, "Ronda 2 (Vuelta)")]
                    ),
                ),
                ("fecha_nro", models.SmallIntegerField()),
                ("played", models.BooleanField(default=False)),
                ("goles_local", models.IntegerField(blank=True, null=True)),
                ("goles_visitante", models.IntegerField(blank=True, null=True)),
                ("programada_en", models.DateTimeField(blank=True, null=True)),
                (
                    "local",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fixture_partidos_local",
                        to="ligas.equipo",
                    ),
                ),
                (
                    "torneo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fixture_partidos",
                        to="ligas.torneo",
                    ),
                ),
                (
                    "visitante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fixture_partidos_visitante",
                        to="ligas.equipo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partido de fixture",
                "verbose_name_plural": "Partidos de fixture",
                "ordering": [
                    "torneo__liga__temporada",
                    "torneo__nombre",
                    "ronda",
                    "fecha_nro",
                    "local__club__nombre",
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("local", models.F("visitante")), _negated=True
                        ),
                        name="chk_fixture_local_distinto_visitante",
                    ),
                    models.UniqueConstraint(
                        fields=("torneo", "ronda", "fecha_nro", "local", "visitante"),
                        name="uq_partido_fixture",
                    ),
                ],
            },
        ),
    ]
