# Generated by Django 5.2.6 on 2025-09-24 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ligas", "0006_alter_categoria_options_alter_equipo_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partidofixture",
            name="goles_local",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="partidofixture",
            name="goles_visitante",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ResultadoCategoriaPartido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("goles_local", models.PositiveIntegerField()),
                ("goles_visitante", models.PositiveIntegerField()),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultados_partidos_fixture",
                        to="ligas.categoria",
                    ),
                ),
                (
                    "partido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultados_por_categoria",
                        to="ligas.partidofixture",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resultado por categoría",
                "verbose_name_plural": "Resultados por categoría",
                "ordering": [
                    "partido__torneo__liga__temporada",
                    "partido__torneo__nombre",
                    "partido__ronda",
                    "partido__fecha_nro",
                    "categoria__nombre",
                ],
                "unique_together": {("partido", "categoria")},
            },
        ),
    ]
