# Generated by Django 5.2.6 on 2025-09-24 16:18

import django.db.models.deletion
from django.db import migrations, models


def asignar_clubes_fixture(apps, schema_editor):
    FixturePartido = apps.get_model("ligas", "FixturePartido")

    for partido in FixturePartido.objects.select_related(
        "local_equipo__club", "visitante_equipo__club"
    ).iterator():
        local_equipo = getattr(partido, "local_equipo", None)
        visitante_equipo = getattr(partido, "visitante_equipo", None)

        if local_equipo is not None:
            partido.local_id = local_equipo.club_id
        if visitante_equipo is not None:
            partido.visitante_id = visitante_equipo.club_id

        partido.save(update_fields=["local", "visitante"])


class Migration(migrations.Migration):

    dependencies = [
        ("ligas", "0006_alter_categoria_options_alter_equipo_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categoria",
            options={
                "ordering": ["liga__temporada", "liga__nombre", "nombre"],
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
            },
        ),
        migrations.AlterModelOptions(
            name="equipo",
            options={
                "ordering": [
                    "categoria__liga__temporada",
                    "categoria__nombre",
                    "club__nombre",
                ],
                "verbose_name": "Equipo",
                "verbose_name_plural": "Equipos",
            },
        ),
        migrations.AlterModelOptions(
            name="fixturepartido",
            options={
                "ordering": [
                    "torneo__liga__temporada",
                    "torneo__nombre",
                    "ronda",
                    "fecha_nro",
                    "local__nombre",
                ],
                "verbose_name": "Partido de fixture",
                "verbose_name_plural": "Partidos de fixture",
            },
        ),
        migrations.RemoveConstraint(
            model_name="fixturepartido",
            name="uq_partido_fixture",
        ),
        migrations.RemoveConstraint(
            model_name="fixturepartido",
            name="chk_fixture_local_distinto_visitante",
        ),
        migrations.RenameField(
            model_name="fixturepartido",
            old_name="local",
            new_name="local_equipo",
        ),
        migrations.RenameField(
            model_name="fixturepartido",
            old_name="visitante",
            new_name="visitante_equipo",
        ),
        migrations.AddField(
            model_name="fixturepartido",
            name="local",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fixture_partidos_local",
                to="ligas.club",
            ),
        ),
        migrations.AddField(
            model_name="fixturepartido",
            name="visitante",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fixture_partidos_visitante",
                to="ligas.club",
            ),
        ),
        migrations.RunPython(asignar_clubes_fixture, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="fixturepartido",
            name="local",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fixture_partidos_local",
                to="ligas.club",
            ),
        ),
        migrations.AlterField(
            model_name="fixturepartido",
            name="visitante",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fixture_partidos_visitante",
                to="ligas.club",
            ),
        ),
        migrations.RemoveField(
            model_name="fixturepartido",
            name="local_equipo",
        ),
        migrations.RemoveField(
            model_name="fixturepartido",
            name="visitante_equipo",
        ),
        migrations.AddConstraint(
            model_name="fixturepartido",
            constraint=models.CheckConstraint(
                check=models.Q(("local", models.F("visitante")), _negated=True),
                name="chk_fixture_local_distinto_visitante",
            ),
        ),
        migrations.AddConstraint(
            model_name="fixturepartido",
            constraint=models.UniqueConstraint(
                fields=("torneo", "ronda", "fecha_nro", "local", "visitante"),
                name="uq_partido_fixture",
            ),
        ),
    ]
